### ISSUE TITLE
classref file 

### ISSUE THREAD

**Issue by ssscj** [darelab2014/Dinopore#3]
Hi,
Thanks for developing Dinopore. I want to use Dinopore to quantify the A-to-I editing events in my nanopore data, so I followed the steps to process the data. In step 5 and step 6 of testing path, classref file is required, and I don't know what this classref file is . In the training path step5,  note 2 says classref file is the groundtruth_training_file. I want to use Dinopore to predict the edit rate of my data,  so I don't have the ground truth file. How could I use Dinopore? Thanks.

Best regards,
Chujie

**Comment by skchronicles** [comment]
@ssscj 
Is there any update on this issue? I am also in the same situation. I am not sure what I should be providing as the ground truth file. I am not sure if this file is only being used to assess accuracy/precision of the model, or if it is being used for something else more important.

@darelab2014 @hengjwj @tramanh183 
If you could provide some clarification, that would be awesome!

Thank you again for your time and help. I appreciate it!

**Comment by hengjwj** [comment]
Hi @ssscj , @skchronicles,

Sorry for the late reply and thanks for trying out our method. The classref file is used to assess the model's prediction based on Illumina sequencing data. The file for training and testing are of different formats. I've moved the files over from Code Ocean for convenience. For the training file, please see /Dinopore/code/misc/Example_ground_truth_training.txt. For testing, please see /Dinopore/code/misc/Example_classref.txt.

**Comment by howwin-sdu** [comment]
Hi @hengjwj , @ssscj , and @skchronicles ,

Thank you all for the earlier discussion — I’m currently in the same situation.

I would like to use Dinopore to quantify A-to-I RNA editing events in my own Nanopore direct RNA dataset, following the testing path. However, I'm not sure how to generate the required classref file in steps 5 and 6, since I don’t have matched Illumina data or ground truth editing sites.

@hengjwj  – I understand from your previous reply that the classref file is used for accuracy assessment, and that /misc/Example_classref.txt serves as a reference example. But if we only want to obtain predicted editing sites and estimated editing rates (not compute accuracy), is it possible to proceed without the classref file? Or is there a way to create a dummy or minimal version of this file?

@ssscj  @skchronicles  – I saw that you had similar questions. I wonder if you’ve found a solution or workaround? It would be very helpful if you could share your experience.

Many thanks in advance!

Best regards,
haowen
